version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service_app
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - user_network

  mysql:
    image: mysql:8.0.35
    container_name: user_service_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - user_network

  redis:
    image: redis:7.2-alpine
    container_name: user_service_redis
    restart: unless-stopped
    networks:
      - user_network

networks:
  user_network:
    driver: bridge

volumes:
  dbdata:
